---
- name: Update and upgrade apt packages
  apt:
    upgrade: yes
    update_cache: yes

- name: Install required packages
  apt:
    name:
      - docker.io
      - docker-compose
    state: present

- name: Ensure Docker service is running
  systemd:
    name: docker
    state: started
    enabled: yes