---
- name: Install Monitoring Agents on Eth Nodes
  hosts: ethereum_nodes
  become: yes
  vars:
    node_exporter_version: 1.3.1
    promtail_version: 2.6.1
    monitoring_server: "{{ hostvars[groups['monitoring'][0]]['ansible_host'] }}"
  roles:
    - monitoring/monitoring_agents_eth_nodes