---
- name: Install required packages
  apt:
    name:
      - curl
      - tar
    state: present
    update_cache: yes

- name: Download and install Node Exporter
  block:
    - name: Download Node Exporter
      get_url:
        url: "https://github.com/prometheus/node_exporter/releases/download/v{{ node_exporter_version }}/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"

    - name: Extract Node Exporter
      unarchive:
        src: "/tmp/node_exporter-{{ node_exporter_version }}.linux-amd64.tar.gz"
        dest: /usr/local/bin
        remote_src: yes
        extra_opts: [--strip-components=1]
        creates: /usr/local/bin/node_exporter

- name: Create Node Exporter systemd service
  template:
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
  notify: 
    - Reload systemd
    - Restart Node Exporter

- name: Download and install Promtail
  block:
    - name: Download Promtail
      get_url:
        url: "https://github.com/grafana/loki/releases/download/v{{ promtail_version }}/promtail-linux-amd64.zip"
        dest: "/tmp/promtail-linux-amd64.zip"

    - name: Install unzip
      apt:
        name: unzip
        state: present

    - name: Extract Promtail
      unarchive:
        src: "/tmp/promtail-linux-amd64.zip"
        dest: /usr/local/bin
        remote_src: yes
        creates: /usr/local/bin/promtail-linux-amd64

- name: Create Promtail configuration
  template:
    src: promtail-config.yml.j2
    dest: /etc/promtail-config.yml
  notify: Restart Promtail

- name: Create Promtail systemd service
  template:
    src: promtail.service.j2
    dest: /etc/systemd/system/promtail.service
  notify:
    - Reload systemd
    - Restart Promtail

- name: Ensure Node Exporter and Promtail are started and enabled
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop:
    - node_exporter
    - promtail
