all:
  children:
    monitoring:
      hosts:
        monitor:
          ansible_host: 146.67.30.175
          # private_ip: 192.168.10.1
          private_ip_wireguard: 192.168.10.1
          private_ip_contabo_network: 10.0.0.1
    ethereum_nodes:
      hosts:
        node1:
          ansible_host: 146.67.34.60
          private_ip_wireguard: 192.168.10.2
          # private_ip: 192.168.10.2
          private_ip_contabo_network: 10.0.0.3
        node2:
          ansible_host: 146.67.24.62
          private_ip_wireguard: 192.168.10.3
          # private_ip: 192.168.10.3
          private_ip_contabo_network: 10.0.0.2
        node3:
          ansible_host: 146.67.24.68
          private_ip_wireguard: 192.168.10.4
          # private_ip: 192.168.10.4
          private_ip_contabo_network: 10.0.0.4
  vars:
    ansible_user: root
    ansible_ssh_private_key_file: path/to/your/private_key